spring.application.name=oniondemo


spring.profiles.active=production
logging.level.root=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN
spring.sql.init.mode=never

spring.main.banner-mode=off
